name: fastdvdnet
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.0
  - future=0.18.2
  - opencv=4.4.0
  - mkl=2020.4
  - pip=21.2.4
  - pycodestyle=2.6.0
  - pytest=6.1.2
  - python=3.8
  - pytorch=1.7.0
  - scikit-image=0.17.2
  - torchvision=0.8.1
  - pip:
    - --extra-index-url https://developer.download.nvidia.com/compute/redist nvidia-dali-cuda110==1.13.0
    - tensorboardx==2.1

